ARG NODE_VERSION=node:20
ARG ALPINE_VERSION=alpine3.18

FROM ${NODE_VERSION}-${ALPINE_VERSION} as base

ARG CLIENT_ID
ENV CLIENT_ID=$CLIENT_ID

ARG CLIENT_SECRET
ENV CLIENT_SECRET=$CLIENT_SECRET

ARG REDIRECT_URL
ENV REDIRECT_URL=$REDIRECT_URL

ENV HEADLESS=1

ARG PRIVATE_KEY
ENV PRIVATE_KEY=$PRIVATE_KEY

ARG PUBLIC_KEY
ENV PUBLIC_KEY=$PUBLIC_KEY

ARG ADMIN_PUB_KEY
ENV ADMIN_PUB_KEY=$ADMIN_PUB_KEY

ARG ADMIN_PASSWORD
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD

ARG USER_PASSWORD
ENV USER_PASSWORD=$USER_PASSWORD

ARG COOKIE_KEY
ENV COOKIE_KEY=$COOKIE_KEY

ARG CORS
ENV CORS=$CORS

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_NAME
ENV DB_NAME=$DB_NAME

ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD

ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME

WORKDIR /home/node/app

COPY package*.json ./
COPY tsconfig.json ./
RUN npm i -g typescript
RUN npm i

FROM base as build

COPY ./src ./src
RUN npm run build

FROM base as final
WORKDIR /home/node/app
ENV NODE_ENV=production
COPY --from=build /home/node/app/dist ./
COPY ./src/templates ./src/templates
ENV CLIENT_ID=$CLIENT_ID
ENV CLIENT_SECRET=$CLIENT_SECRET
ENV REDIRECT_URL=$REDIRECT_URL
ENV HEADLESS=1
ENV PRIVATE_KEY=$PRIVATE_KEY
ENV PUBLIC_KEY=$PUBLIC_KEY
ENV ADMIN_PUB_KEY=$ADMIN_PUB_KEY
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV USER_PASSWORD=$USER_PASSWORD
ENV COOKIE_KEY=$COOKIE_KEY
ENV CORS=$CORS
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV DB_HOST=$DB_HOST
ENV DB_NAME=$DB_NAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_USERNAME=$DB_USERNAME
# Set the path to Chromium executable
ENV CHROME_BIN=/usr/bin/chromium-browser
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

EXPOSE 8080

CMD ["node", "main.js"]