on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Authenticate with GCP
      run: |
        gcloud config set project ad-youtubefy
        echo -n "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/key.json
        gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=/tmp/key.json

    - name: Build Docker Image
      run: |
        docker build . ${{ secrets.BUILD_ARGS }} -t us-east1-docker.pkg.dev/ad-youtubefy/youtubefy-server/test-prod:latest
        docker push us-east1-docker.pkg.dev/ad-youtubefy/youtubefy-server/test-prod:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud config set project ad-youtubefy
        gcloud config set run/region us-east1
        gcloud auth configure-docker us-east1-docker.pkg.dev
        docker pull us-east1-docker.pkg.dev/ad-youtubefy/youtubefy-server/test-prod:latest
        gcloud run deploy youtubefy --image=us-east1-docker.pkg.dev/ad-youtubefy/youtubefy-server/test-prod:latest --platform=managed --region=us-east1 --allow-unauthenticated --cpu=1 --memory=512Mi --min-instances=0 --max-instances=1 --concurrency=30
      env: 
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
